config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'events/index'
  get 'events/show'
  devise_for :users
  root to: "events#index"
 
  resources :events do
    resources :bookings
    resources :chatrooms, only: :show
  end

  resources :bookings
  resources :users, only: %i[show edit update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :user_id, uniqueness: { scope: :event_id, message: "has already booked this event" }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookings = policy_scope(Booking)

    @upcoming_bookings = @bookings.joins(:event).where('events.date >= ?', Date.today).order('events.date ASC')
    @past_bookings = @bookings.joins(:event).where('events.date < ?', Date.new(2024, 5, 24)).order('events.date DESC')
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @event = Event.find(params[:event_id])
    @booking = Booking.new(event: @event)
    authorize @event
    authorize @booking
  end

  def create
    @booking = current_user.bookings.new(booking_params)
    @event = Event.find(params[:event_id])
    @booking.event = @event
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to @event, alert: @booking.errors.full_messages.to_sentence
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.user == current_user
      @booking.destroy
      redirect_to bookings_path, notice: 'Booking has been removed'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:event_id, :user_id, :confirmed, :number_of_tickets)
  end
end

app/views/bookings/index.html.erb
<br>
<br>
<br>
<br>
<div class="content-container">
<div class="past-events">
  <% if @upcoming_bookings.any? %>
    <div>
      <h1 class="your-bookings">Your Events</h1>
      <div class="separator"></div>
      <h5 class="subtitle">Looking forward to seeing you there!</h5>
    </div>
    <div class="row row-cols-1 row-cols-md-3 mt-3">
      <% @upcoming_bookings.each do |booking| %>
      <div class="col mb-4">
        <div class="card event-card">
          <%= cl_image_tag booking.event.photos[0].key, class: "card-img-top castle-image" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to booking.event.name, booking_path(booking), class: "event-link" %></h5>
            <p class="card-text"><strong>Location:</strong> <%= booking.event.location %></p>
            <p class="card-text"><strong>Date:</strong> <%= booking.event.start_time.strftime("%A %d %B %Y") %></p>
            <p class="card-text"><strong>Time:</strong> <%= booking.event.start_time.strftime("%H:%M") %> - <%= booking.event.end_time.strftime("%H:%M") %></p>
          </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>You have no bookings.</p>
    <%= link_to "Browse events", events_path, class: "btn btn-secondary" %>
  <% end %>
  <br>
  <br>
  <br>
  <div>
    <h1 class="your-bookings">Your Events History</h1>
    <div class="separator"></div>
    <% if @past_bookings.any? %>
      <h5 class="subtitle">Hope you enjoyed the event!</h5>
      <div class="row row-cols-1 row-cols-md-3 mt-3">
        <% @past_bookings.each do |booking| %>
        <div class="col mb-4">
          <div class="card event-card">
            <%= cl_image_tag booking.event.photos[0].key, height: 250, crop: :fill, class: "castle-image" %>
            <div class="card-body">
              <h5 class="card-title"><%= link_to booking.event.name, booking_path(booking), class: "event-link" %></h5>
              <p class="card-text"><strong>Location:</strong> <%= booking.event.location %></p>
              <p class="card-text"><strong>Date:</strong> <%= booking.event.start_time.strftime("%A %d %B %Y") %></p>
              <p class="card-text"><strong>Time:</strong> <%= booking.event.start_time.strftime("%H:%M") %> - <%= booking.event.end_time.strftime("%H:%M") %></p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    <% else %>
      <h5 class="subtitle">Your events history is empty</h5>
      <%= link_to "Browse events", events_path, class: "btn btn-secondary" %>
    <% end %>
    </div>
  </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5 d-flex justify-content-center align-items-center">

  <%= simple_form_for [@event, @booking] do |f| %>
      <div class="bookings-new-form">
        <div class="d-flex align-items-center">
          <%= link_to "⇦", events_path, class: "btn btn-secondary me-3" %>
          <h1 id="booking-headings" class="mb-0">Book: <%= @event.name %></h1>
        </div>
        <br>
        <%= cl_image_tag @event.photos[0].key, width: 600, height: 400, crop: :fill, class: "hero" %>
        <br>
        <div class="book-tickets-section">

          <div class="d-flex align-items-center mt-3">

            <div class="form-input">
              <%= f.label :first_name, class: "bold-label" %>
              <p><%= current_user.first_name %></p>
            </div>

            <div class="form-input">
              <%= f.label :email, class: "bold-label" %>
              <p><%= current_user.email %></p>
            </div>

            <div class="form-input">
              <%= f.label :date, class: "bold-label" %>
              <p><%= @event.start_time.strftime("%A %d %B %Y") %></p>
            </div>

          </div>

          <div class="d-flex align-items-center mt-3">

            <div class="form-input">
              <%= f.label :start_time, as: :time, class: "bold-label" %>
              <p><%= @event.start_time.strftime("%H:%M") %></p>
            </div>

            <div class="form-input">
              <%= f.label :end_time, as: :time, class: "bold-label" %>
              <p><%= @event.end_time.strftime("%H:%M") %></p>
            </div>


          </div>
          <div class="d-flex align-items-center mt-3">
            <div class="form-input">
              <%= f.label :number_of_tickets, class: "bold-label" %>
              <br>
              <%= f.number_field :number_of_tickets, min: 1, value: 1 %>
            </div>
            <br>
            <%= f.button :submit, "Book Event",  class: "btn btn-primary"  %>
            <br>
          </div>
        </div>
      </div>
  <% end %>
<div>

app/views/bookings/show.html.erb
<br>
<br>
<div class="container mt-5 booking-details-container">
  <div class="d-flex align-items-center">
    <%= link_to "⇦", events_path, class: "btn btn-secondary me-3" %>
    <h1 id="booking-headings" class="mb-0">Booking Details</h1>
  </div>
  <br>
  <p id="booking-subtitle"><strong>Event:</strong> <%= @booking.event.name %></p>
  <br>
  <%= cl_image_tag @booking.event.photos[0].key, height: 250, crop: :fill, class: "hero" %>
  <div class="d-flex mt-5">
    <p id="booking-headings"><strong>Description:</strong> <%= @booking.event.description %></p>
  </div>

  <div class="d-flex align-items-center mt-5">
    <p id="booking-headings"><strong> Date:</strong> <%= @booking.event.start_time.strftime("%A %d %B %Y")%> </p>
    <p id="booking-headings"><strong> Start Time:</strong> <%= @booking.event.start_time.strftime("%H:%M")%> </p>
    <p id="booking-headings"><strong> End Time:</strong> <%= @booking.event.end_time.strftime("%H:%M")%> </p>
  </div>
  <div class="d-flex align-items-center mt-5">
    <p id="booking-headings"><strong>Tickets:</strong> <%= @booking.number_of_tickets %></p>
    <p id="booking-headings"><strong>Confirmed:</strong> <%= 'Yes' %></p>
    <p id="booking-headings"><strong>User:</strong> <%= @booking.user.email %></p>
  </div>
  <div class="booking-links justify-content-start mt-3">
    <%= link_to "Delete", booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }, class: "btn btn-danger" %>
    <%= link_to "View your events", bookings_path, class: "btn btn-secondary" %>
      <% if current_user.bookings.where(event: @booking.event) %>
        <%= link_to event_chatroom_path(@booking.event), class: "btn btn-secondary" do %>
        <i class="far fa-comment-alt"></i>
        <% end %>
      <% end %>
  </div>
</div>
<br>
<br>
<br>
<br>