config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'events/index'
  get 'events/show'
  devise_for :users
  root to: "events#index"
 
  resources :events do
    resources :bookings
    resources :chatrooms, only: :show
  end

  resources :bookings
  resources :users, only: %i[show edit update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :events, dependent: :destroy
  has_one_attached :photo
  has_many :messages

  validates :first_name, :last_name, :username, presence: true
  validates :email, :password, presence: true
  validates :bio, length: { maximum: 500 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @user = User.find(params[:id])
    @created_events = @user.events # Events created by the user
    booked_events = @user.bookings
    @user_bookings = booked_events.map do |booking|
      booking.event
    end
    @calendar_events = @created_events + @user_bookings
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :photo, :first_name, :last_name, :password)
  end
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<br>
<br>
<br>
<div class="container mt-5">
  <%= link_to "⇦", events_path, class: "btn btn-secondary" %>
  <br>
  <br>
  <div class="row align-items-center" id="profile-box">
    <div class="col-md-4 d-flex justify-content-center">
      <% if @user.photo.present? %>
        <div class="user-avatar">
          <%= cl_image_tag(@user.photo.key, alt: @user.username, class: 'img-fluid rounded-circle user-image') %>
        </div>
      <% end %>
    </div>
    <div class="col-md-8">
      <h1 class="display-4"><%= @user.username %></h1>
      <p class="lead">Email: <%= @user.email %></p>
      <p class="profile"><%= @user.bio %></p>
      <!--<% if user_signed_in? && current_user == @user %>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-primary mt-3' %>
      <% end %>-->
    </div>
  </div>
  <br>
  <div>
    <h2 id="profile-headings"> My events </h2>
    <%= month_calendar(events: @calendar_events) do |date, events|%>
      <%= date %>
      <% events.each do |event| %>
        <div class="event">
          <p><%= link_to event.name, event_path(event) %></p>
          <br>
        </div>
      <% end %>
    <% end %>
  <div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>