config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'events/index'
  get 'events/show'
  devise_for :users
  root to: "events#index"
 
  resources :events do
    resources :bookings
    resources :chatrooms, only: :show
  end

  resources :bookings
  resources :users, only: %i[show edit update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <!-- Links Column for Contact Us and Help -->
  <div class="footer-section">
    <p class="text">Contact us</p>
    <p class="text">Help</p>
    <div class="social-icons">
      <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a>
      <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
      <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
      <a href="#" class="social-icon"><i class="fab fa-linkedin-in"></i></a>
      <a href="#" class="social-icon"><i class="fab fa-github"></i></a>
    </div>
    <p class="text">©2024 Codeventures, Inc.</p>
  </div>

  <!-- Address Column on the Far Right -->
  <div class="info">
    <p class="text">
      Codeventures<br>
      22 Roboto Lane<br>
      Techtown, CV1 2FT<br>
      United Kingdom<br>
      Tel: +44 131 555 1234<br>
      Email: contact@codeventures.co.uk
    </p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar sidebar">
  <div class="container-fluid">
    <%= link_to events_path, class: "navbar-brand" do %>
      <%= image_tag "/img/logo_white.png" %>
    <% end %>

    <%# <button class="navbar-toggler" type="button" data-action="click->sidebar#toggle" aria-label="Toggle sidebar">
      <span class="navbar-toggler-icon"> %>
        <i class="fas fa-bars fa-2xl text-white" id="burger-menu" data-action="click->sidebar#toggle"></i>
      <%# </span>
    </button> %>

    <div class="sidebar d-none" data-sidebar-target="menu">
      <div class="ava-tar">
        <h1 class="closing-arrow" data-action="click->sidebar#toggle">></h1>
        <ul class="navbar-nav me-auto" id="sidebar-bits">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <% if current_user.photo.present? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                  <img src="default_avatar.png" class="avatar" alt="default avatar">
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="side-list">
        <ul>
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Your events", bookings_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Add new event", new_event_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>