config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'events/index'
  get 'events/show'
  devise_for :users
  root to: "events#index"
 
  resources :events do
    resources :bookings
    resources :chatrooms, only: :show
  end

  resources :bookings
  resources :users, only: %i[show edit update]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include PgSearch::Model
  acts_as_taggable_on :tags

  pg_search_scope :search_by_details,
    against: [:name, :description, :keywords, :location],
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode
  has_one :chatroom, dependent: :destroy
  has_many :bookings
  has_many :users, through: :bookings

  after_create :create_chatroom

  private

  def create_chatroom
    @chatroom = Chatroom.create(event: self)
    # @chatroom = Chatroom.new
    # @event = Event.find(params[:id])
    # @chatroom.event = @event
    # @chatroom.save
    # raise
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :destroy]

  def index
    @events = Event.all

    if params[:query].present? || params[:tag].present?
      @tags = ActsAsTaggableOn::Tagging.where(taggable_type: "Event").map { |tagging| tagging.tag }.uniq
      @events = Event.tagged_with(params[:tag]) if params[:tag].present? && params[:tags] != [""]
      @events = Event.search_by_details(params[:query]) if params[:query].present? && params[:query] != [""]
      @upcoming_events = @events.where('date >= ?', Date.new(2024, 5, 27)).order('date ASC')
      @past_events = @events.where('date < ?', Date.new(2024, 5, 27)).order('date DESC')
      @query = params[:query]

    else
      @upcoming_events = @events.where('date >= ?', Date.new(2024, 5, 24)).order('date ASC')
      @past_events = @events.where('date < ?', Date.new(2024, 5, 24)).order('date DESC')
    end
  end

  def show
    @event = Event.find(params[:id])
    @chatroom = @event.chatroom
    authorize @event
    @markers =
    [{
      lat: @event.latitude,
      lng: @event.longitude
    }]
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      @chatroom = Chatroom.new
      @chatroom.event = @event
      @chatroom.save
      redirect_to event_path(@event)
    else
      puts @event.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
    authorize @event
  end

  def update
    @event = Event.find(params[:id])
    authorize @event
    if @event.update(event_params)
      redirect_to @event, notice: 'Updated Successfully!'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorize @event
    if @event.destroy
      redirect_to events_path, notice: 'Event was successfully deleted.'
    else
      redirect_to events_path, alert: 'You are not authorized to delete this event.'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :start_time, :end_time, :keywords, photos: [])
  end
end

app/views/events/edit.html.erb
<div class="container mt-5">
  <div class="edit-event">
    <div class="d-flex align-items-center">
      <%= link_to "⇦", events_path, class: "btn btn-secondary me-3" %>
      <h1 id="booking-headings" class="mb-0"> Edit event </h1>
    </div>
      <%= simple_form_for(@event) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :date, as: :string,
                  input_html: { data: { controller: "datepicker" } } %>
        <%= f.input :start_time, as: :time %>
        <%= f.input :end_time,  as: :time  %>
        <%= f.input :keywords %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Edit", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div data-controller='scroll'>
  <div class="video-container" data-controller="search">
    <video autoplay muted loop>
      <source src="/videos/matrix.mp4" type="video/mp4">
      Your browser does not support the video tag.
    </video>


    <% if @query || @tags %>

    <% end %>



    <div class="search-container" >
      <h2 class="search-title">Find Your Next Codeventure!</h2>
        <%= form_with url: events_path, method: :get, local: true, class: "d-flex", data: { turbo: false } do %>
        <div class="form-group mb-0">
          <%= text_field_tag :query, params[:query], placeholder: "Search events...", class: "form-control large-search-input" %>
        </div>
        <div class="form-group mb-0">
          <%= submit_tag "Search", class: "btn btn-primary", id: "search-button" %>
        </div>
      <% end %>
      <div class="tags-bar mt-3 mb-3 text-center" id="tags-green" >
      <% Event.tag_counts_on(:tags).each do |tag| %>
        </li><%= link_to tag.name, events_path(tag: tag.name), class: "btn btn-outline-primary btn tag-button-white mx-1", data: { turbo: false } %>
      <% end %>
      </div>
    </div>
  </div>


  <div data-scroll-target='events'>
      <% if @query || @tags %>
        <div class="content-container" data-search-target="events">
      <% else %>
        <div class="content-container" data-search-target="events">
      <% end %>
        <div class="past-events">
        <% if @upcoming_events.any? %>
          <h2 id="home-page-headings">Upcoming Events</h2>
          <div class="row row-cols-1 row-cols-md-3 mt-3">
            <% @upcoming_events.each do |event| %>
              <div class="col mb-4">
                <div class="card event-card">
                  <%= cl_image_tag event.photos.first.key, class: "card-img-top castle-image" if event.photos.attached? %>
                  <div class="card-body">
                    <h5 class="card-title"><%= link_to event.name, event_path(event), class: "event-link" %></h5>
                    <p class="card-text"><strong>Location:</strong> <%= event.location %></p>
                    <p class="card-text"><strong>Date:</strong> <%= event.start_time.strftime("%A %d %B %Y") %></p>
                    <p class="card-text"><strong>Time:</strong> <%= event.start_time.strftime("%H:%M") %> - <%= event.end_time.strftime("%H:%M") %></p>
                    <%= link_to "Find out more", event_path(event), class: "button-56" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="past-events">
    <% if @past_events.any? %>
      <h2 id="home-page-headings">Past Events</h2>
      <div class="row row-cols-1 row-cols-md-3 mt-3">
        <% @past_events.each do |event| %>
          <div class="col mb-4">
            <div class="card event-card">
              <%= cl_image_tag event.photos.first.key, class: "card-img-top castle-image" if event.photos.attached? %>
              <div class="card-body">
                <h5 class="card-title"><%= link_to event.name, event_path(event), class: "event-link" %></h5>
                <p class="card-text"><strong>Location:</strong> <%= event.location %></p>
                <p class="card-text"><strong>Date:</strong> <%= event.start_time.strftime("%A %d %B %Y") %></p>
                <p class="card-text"><strong>Time:</strong> <%= event.start_time.strftime("%H:%M") %> - <%= event.end_time.strftime("%H:%M") %></p>
                <%= link_to "Find out more", event_path(event), class: "button-56" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-5">
  <div class="new-event">
    <div class="d-flex align-items-center">
      <%= link_to "⇦", events_path, class: "btn btn-secondary me-3" %>
      <h1 id="booking-headings" class="mb-0"> Add an event </h1>
    </div>
      <%= simple_form_for(@event) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :date, as: :string,
                  input_html: { data: { controller: "datepicker" } } %>
        <%= f.input :start_time, as: :time %>
        <%= f.input :end_time,  as: :time  %>
        <%= f.input :keywords %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container mt-5 event-show-container">
<br>
  <div class="d-flex align-items-center">
    <%= link_to "⇦", events_path, class: "btn btn-secondary me-3" %>
    <h1 id="event-heading" class="mb-0"><%= @event.name %></h1>
  </div>
<br>
  <div class="event-details-card">
    <div class="gallery">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% if @event.photos.present? %>
            <div class="carousel-item active">
              <%= cl_image_tag @event.photos[0].key, width: 1300, height: 500, crop: :fill %>
            </div>
            <% @event.photos.each_with_index do |photo, index| %>
              <% next if index == 0 %>
              <div class="carousel-item">
                <%= cl_image_tag photo.key, width: 1300, height: 500, crop: :fill %>
              </div>
            <% end %>
          <% else %>
            <p>No photo available</p>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>

    <div class="details-and-goers-container d-flex">
      <div class="details">
        <p><%= @event.description %></p>
        <p>Location: <%= @event.location %></p>

        <p>Hosted by: <%= link_to user_path(@event.user) do %><%= cl_image_tag @event.user.photo.key, width: 50, height: 50, crop: :thumb, alt: "#{@event.user.first_name}'s profile photo" %>
        <% end %>

        <p>Keywords: #<%= @event.keywords %></p>
        <hr>
        <div class="datetime-button-container d-flex">
          <div class="datetime-container">
            <p>Date: <%= @event.start_time.strftime("%A %d %B %Y") %></p>
            <p>Start time: <%= @event.start_time.strftime("%H:%M") %></p>
            <p>End time: <%= @event.end_time.strftime("%H:%M") %></p>
          </div>
          <div class="button-container ms-4">
            <%= link_to "Book", new_event_booking_path(@event), class: "btn btn-primary" %>
            <%= link_to events_path, class: "btn btn-secondary" do %>
              <i class="fa-solid fa-chevron-left"></i> Back to Events
            <% end %>
            <% if policy(@event).edit? %>
              <%= link_to 'Edit Event', edit_event_path(@event), class: "btn btn-" %>
            <% end %>
            <% if policy(@event).destroy? %>
              <%= link_to 'Delete Event', event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="event-goers">
        <h4 id="event-goers" class="text-center">Who's going...</h4>
        <hr>
        <% if @event.users.empty? %>
          <p class="text-center">Be the first to book this event!</p>
        <% else %>
          <ul class="no-bullets">
            <% @event.users.each do |user| %>
              <li id="user-going">
                <%= cl_image_tag user.photo.key, width: 50, height: 50, crop: :thumb, alt: "#{user.first_name}'s profile photo" %>
                <%= user.first_name %>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>


  </div>
</div>
 <div class="map container mt-5 ">
      <div style="width: 100%; height: 400px;"
           data-controller="map"
           data-map-markers-value="<%= @markers.to_json %>"
           data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>